domain_path: D:\PrjMig-Vitis_2024.1\repos\arty-z7\sw\ws_20250227084436\hdmi_in_wrapper\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
